### PR TITLE
Add full param options for monitors

### PR DESCRIPTION
**Pull request by Seanstoppable**
Add a more generic function that will let people mix and match
Have existing functions wrap this better function
Resolves the rest of state support in #164

### CODE REVIEW

**Comment by Seanstoppable** [comment]
@ojongerius Hey, just wanted to follow up on this, now that we are through the holidays 😄

**Comment by chirauki** [comment]
Hi there, any progress on this one? Could really use the feature. I'm happy to open a new PR with a rebased version if @Seanstoppable is not available.

**Comment by Seanstoppable** [comment]
I'm happy to re-pick up this work

**Comment by Seanstoppable** [comment]
@chirauki rebased

**Comment by chirauki** [comment]
So cool! I guess someone will nned to take a look, approve and merge? @ojongerius maybe?

**Comment by bkabrda** [comment]
This looks awesome, thanks a bunch for doing it. Everything looks fine, so I'm going to merge right now. 👍

**Pull request merged**
