### PR TITLE
[WIP] Support for /v0/synthetics [Waiting public BETA]

### PR DESCRIPTION
**Pull request by dharada1**
https://github.com/zorkian/go-datadog-api/issues/204

### CODE REVIEW

**Comment by dharada1** [comment]
I want to add integration test, but I should not do it yet because it's closed beta ( see #204 )

**Comment by dharada1** [comment]
now it's public, I will fix it for public version
https://www.datadoghq.com/blog/introducing-synthetic-monitoring/

**Comment by btoueg** [comment]
Hey @dharada1 ! I'm from Datadog synthetics and I would like to thank you for making this PR.

I wanted to let you know that we plan on having go-datadog-api support synthetics soon (see attached PR) and that we are in the process of renaming the endpoints for the v1.

We'll take the work you've done from here if that's ok with you!

**Comment by dharada1** [comment]
@btoueg Thanks a lot! Should I close this PR?

**Pull request closed without merging**
