### PR TITLE
Adding Integration Tests in TravisCI

### PR DESCRIPTION
**Pull request by MattHodge**
* Adds the integration tests to TravisCI (4 currently fail).
* Hopefully, this helps with #39.

You just need to add `DATADOG_API_KEY` and `DATADOG_APP_KEY` to the [TravisCI environment variables](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings).

### CODE REVIEW

**Comment by yfronto** [comment]
Thanks for the PR @MattHodge! 

@zorkian, @ojongerius - Isn't there a test account? I can request one from Datadog, but I thought there was already one for this purpose.

**Comment by ojongerius** [comment]
I've added them to Travis. @yfronto shall I invite you to the DD account if so what email address?

**Comment by yfronto** [comment]
Sure thing. As Github doesn't do PMs anymore, I added you to https://github.com/yfronto/contact that has my info.

**Comment by MattHodge** [comment]
I have updated this so PR builds to not run acceptance tests. This will prevent every PR appearing red.

I'd suggest scheduling a TravisCI cron run to valid acceptance tests and use a badge to display info: https://docs.travis-ci.com/user/cron-jobs/

**Comment by MattHodge** [comment]
Any updates on this one @yfronto or @ojongerius ?

**Pull request merged**
