### PR TITLE
WIP: Screenboards Support

### PR DESCRIPTION
**Pull request by seiffert**
I'd like to work with Screenboards via the API. Would you be ok with this functionality and merge this PR once it became stable?

Right now, I'm still working on it:

- [x] Screenboards CRUD
- [ ] Cover all types of Widgets
    - [x] Timeseries
    - [x] FreeText
    - [x] QueryValue
    - [x] Toplist
    - [x] EventStream
    - [ ] EventTimeline
    - [ ] Image 
    - [ ] Note
    - [ ] AlertGraph
    - [ ] AlertValue
    - [ ] IFrame
- [ ] Share Screenboard
- [ ] Tests

/cc @luzifer

### CODE REVIEW

**Comment by zorkian** [comment]
Oh absolutely; the client library ideally supports all methods that exist in the API. Being able to manage/maintain screenboards totally falls into that.

While I personally haven't needed programmatic access to much more than pushing metrics, it seems pretty interesting to be able to manipulate screenboards automatically. (If you edit them, do logged in viewers see the edits? That'd be killer. I could imagine a really interesting "automatically inserted most relevant graphs" section...)

**Comment by zorkian** [comment]
Is this still something you're working on/sometimes? :)

**Comment by ojongerius** [comment]
Hi @zorkian / @seiffert,

Nice work.

I'm working on a [Datadog provider for Terraform](https://github.com/ojongerius/terraform-provider-datadog) and implementing Screenboard is on my todo list.

@seiffert how is this work going, do you plan on finishing it? @zorkian is this something you would want to work on? If not I might have a stab at it.

**Comment by zorkian** [comment]
@ojongerius I have been busy at work and we don't use Datadog unfortunately so haven't had time to pick it up. I welcome you to pick it up and run with it! (But let us know if not, so someone/me can take it up when time is available.)

**Comment by ojongerius** [comment]
It's blocking an issue I plan to work on next week, so it's in my own interest :smile:

I'll update this PR when I start work, until then; happy for anyone else to pick it up.

**Comment by ojongerius** [comment]
Hey there; just a heads up that I'm giving this one a go. Will update when I have some news.

**Comment by ojongerius** [comment]
Have setup a [branch](https://github.com/ojongerius/go-datadog-api/tree/screenboards) including tests in Travis, and made my self a little more familiar with the codebase. compare master and my screenboards branch [here](https://github.com/zorkian/go-datadog-api/compare/master...ojongerius:screenboards?expand=1).

I plan on adding the last features this Thursday, so if all goes well should have a PR out this week.

**Comment by ojongerius** [comment]
Getting somewhere :smile: 

```sh
✘ ojongerius@hipster  ~/gocode/src/github.com/ojongerius/go-datadog-api   screenboards ●  make testacc
TF_ACC=1 go test integration_test/* -v  -timeout 90m
=== RUN TestAlertValueWidget
--- PASS: TestAlertValueWidget (5.09s)
=== RUN TestChangeWidget
--- PASS: TestChangeWidget (6.14s)
=== RUN TestGraphWidget
--- PASS: TestGraphWidget (5.73s)
=== RUN TestEventTimelineWidget
--- PASS: TestEventTimelineWidget (5.70s)
=== RUN TestAlertGraphWidget
--- PASS: TestAlertGraphWidget (5.50s)
=== RUN TestHostMapWidget
--- PASS: TestHostMapWidget (5.79s)
=== RUN TestCheckStatusWidget
--- PASS: TestCheckStatusWidget (5.70s)
=== RUN TestIFrameWidget
--- PASS: TestIFrameWidget (5.89s)
=== RUN TestNoteWidget
--- PASS: TestNoteWidget (5.20s)
=== RUN TestToplistWidget
--- PASS: TestToplistWidget (6.70s)
=== RUN TestEventSteamWidget
--- PASS: TestEventSteamWidget (9.01s)
=== RUN TestImageWidget
--- PASS: TestImageWidget (5.55s)
=== RUN TestFreeTextWidget
--- PASS: TestFreeTextWidget (5.38s)
=== RUN TestTimeseriesWidget
--- PASS: TestTimeseriesWidget (5.47s)
=== RUN TestQueryValueWidget
--- PASS: TestQueryValueWidget (9.69s)
=== RUN TestCreateAndDeleteScreenboard
--- PASS: TestCreateAndDeleteScreenboard (3.53s)
=== RUN TestShareAndRevokeScreenboard
--- PASS: TestShareAndRevokeScreenboard (5.30s)
=== RUN TestUpdateScreenboard
--- PASS: TestUpdateScreenboard (5.34s)
=== RUN TestGetScreenboards
--- PASS: TestGetScreenboards (5.23s)
PASS
ok  	command-line-arguments	116.219s
```

**Pull request merged**
