### PR TITLE
Support template variables

### PR DESCRIPTION
**Pull request by ojongerius**

### CODE REVIEW

**Comment by zorkian** [comment]
Happy to take the PR, but did this go through `gofmt`? The formatting looks a little unexpected.

**Comment by ojongerius** [comment]
Thanks. It appears Intellij and `gomft` have different opinions. I'll trust `gofmt`.

**Comment by zorkian** [comment]
Awesome, thank you for the pull request and the fast turnaround :)

**Comment by ojongerius** [comment]
That was a fast merge! :boom:

**Pull request merged**
