### PR TITLE
Update downtimes.go

### PR DESCRIPTION
**Pull request by blaketastic2**
There was an additional "m" in the tag

### CODE REVIEW

**Comment by bkabrda** [comment]
Perfect, thanks for the contribution :+1:. Merging.

**Comment by blaketastic2** [comment]
@bkabrda Thanks for getting this merged. What's the typical timeline on getting this into a release?

**Comment by bkabrda** [comment]
Hi @blaketastic2 there is no typical timeline, but I've already been thinking about doing a new release, so I'll probably do it sometime in the first half of the following week.

**Comment by bkabrda** [comment]
@blaketastic2 I've just released v2.21.0: https://github.com/zorkian/go-datadog-api/releases/tag/v2.21.0

**Pull request merged**
