### PR TITLE
Remove `handle` from user update

### PR DESCRIPTION
**Pull request by brendanjerwin**
See: #221 

Introduce a struct for the user update request that doesn't include `handle`.

### CODE REVIEW

**Comment by bkabrda** [comment]
LGTM :+1:. @brendanjerwin are you ok with me squashing the commits into a single one while merging?

**Comment by bkabrda** [comment]
This will also need rebasing now, so please do that. Thanks!

**Comment by dabcoder** [comment]
@brendanjerwin Just catching up on that one, can you do the above? Thanks in advance!

**Comment by brendanjerwin** [comment]
There we go. BTW, Datadog loosened the API constraints that originally prompted me to make this change. However, its probably better to not send the useless field anyway...

**Pull request merged**
