### PR TITLE
Add 'unknown' monitor threshold field

### PR DESCRIPTION
**Pull request by visciang**
This PR adds support for Datadog monitor threshold field.

Giovanni

### CODE REVIEW

**Comment by ojongerius** [comment]
LGTM! I am wondering what the `unknown` threshold does. I can't find a reference to it in regards to monitors at https://docs.datadoghq.com/api/?lang=bash#get-a-monitor-s-details

**Comment by entropiae** [comment]
It looks like it isn't in the documentation (we are opening a PR for the DD API documentation); it set the threshold after which a service check in unknown status trigger a monitor; it's the grey slider in the attached screenshot.
Here there is the documentation service-check side: https://docs.datadoghq.com/agent/agent_checks/#sending-service-checks


screenshot from 2018-01-16 09-13-17

**Comment by ojongerius** [comment]
Thanks for the work and feedback!

**Comment by entropiae** [comment]
Thank you too :smiley:

**Comment by visciang** [comment]
Could you tag a new release, so that I can reference it in the PR I'm opening to `terraform-providers/terraform-provider-datadog`?

**Comment by yfronto** [comment]
@visciang I tagged this commit as v2.8

**Pull request merged**
