### PR TITLE
52

### PR DESCRIPTION
**Pull request by smeshkov**
issue: https://github.com/zorkian/go-datadog-api/issues/52

* expand datadog.Graph.Definition.Request with Aggregator and ConditionalFormats;
* add test

### CODE REVIEW

**Comment by zorkian** [comment]
Can you please `gofmt` it so the tests pass?

**Comment by smeshkov** [comment]
Done

**Comment by zorkian** [comment]
Thank you for the diff!

**Comment by smeshkov** [comment]
Thanks for quick response! So how to track progress on that feature? I mean when it'll be available?

**Pull request merged**
