### PR TITLE
Add several options to Monitor parameter

### LINKED ISSUE #200: Monitor has unsupported params in options key
When I curl a monitor, below parameters are exists.

- API Response
  ```
  ...
  "options": {
    "notify_audit": false,
    "locked": false,
    "timeout_h": 0,
    "silenced": {},
    "enable_logs_sample": true,
    "thresholds": {
      "comparison": ">",
      "critical": 1000,
      "period": {
        "seconds": 300,
        "text": "5 minutes",
        "value": "last_5m",
        "name": "5 minute average",
        "unit": "minutes"
      },
      "timeAggregator": "avg"
    },
    "queryConfig": {
      "logset": {
        "id": "7748",
        "name": "main"
      },
      "timeRange": {
        "to": 1539675566736,
        "live": true,
        "from": 1539661166736
      },
      "queryString": "env:develop",
      "queryIsFailed": false
    }
  ...
  ```

- Unsupported params
  - `queryConfig` in `options`
  - `period` in `thresholds`
  - `comparison` in `thresholds`
  - `timeAggregator` in `thresholds`

But these params are not written in monitor api documents.
- Create: [monitors_create](https://github.com/DataDog/documentation/blob/master/content/api/monitors/monitors_create.md)

### PR DESCRIPTION
**Pull request by kterada0509**
# Related Issue
FIxed #200

## Abstract
Just added unsupported params.

### CODE REVIEW

**Comment by ojongerius** [comment]
@kterada0509 could you expend on why this is marked WIP, did you plan to do more work?

**Comment by kterada0509** [comment]
@ojongerius nothing. just i think should be waited for documents update.

**Comment by bkabrda** [comment]
LGTM 👍 would you mind rebasing this PR @kterada0509 ?

**Comment by bkabrda** [comment]
Thanks for the rebase! Merging.

**Pull request merged**
